version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install --upgrade aws-sam-cli
  build:
    commands:
      - echo Build started on `date`
      - docker build --rm -t btg-backend:latest .
      - docker tag btg-backend:latest wthoutjc/btg-backend:latest
      - sam build --use-container --build-image wthoutjc/btg-backend:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push wthoutjc/btg-backend:latest
      - sam package --output-template-file packaged.yaml --image-repository wthoutjc/btg-backend --region sa-east-1 --s3-bucket lambda-fpv-17-7-24
      - aws cloudformation deploy --template-file packaged.yaml --stack-name btg-backend --capabilities CAPABILITY_IAM --region sa-east-1 --tags Name="Juan Camilo Ramírez Rátiva"
