AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless BTG Pactual - FPV Service

Globals:
  Function:
    Timeout: 300

Resources:
  BTGFunction:
    Type: AWS::Serverless::Function
    Properties:
      ImageUri: wthoutjc/btg-backend:latest
      CodeUri: .
      Handler: app.handler
      Runtime: python3.9
      Timeout: 900
      Events:
        FVPApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Tags:
        Name: "Juan Camilo Ramírez Rátiva"
